# 4.9 Intro to Data Visualization Part 1

## Instacart Grocery Basket Analysis

#### -Errol Hinkamp

##### Table of Contents

1. Import libraries
2. Import data
3. Wrangle and check data
4. Merge data
5. Export data

# 1. Import libraries

In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

# 2. Import data

In [2]:
# Import dataframes
path=r'C:\Users\Errol\Documents\Data Analyst Work\Achievement 4\Instacart Basket Analysis'
customers = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'customers.csv'))
ords_prods_merged = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged_4.8.pkl'))

# 3. Wrangle and check data

In [3]:
# Disable row limits
pd.options.display.max_rows = None

In [4]:
# Quick visual check
customers.head()

,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [5]:
# Get dataframe shape
customers.shape

(206209, 10)

In [6]:
# Get column data
customers.dtypes

user_id          int64
First Name      object
Surnam          object
Gender          object
STATE           object
Age              int64
date_joined     object
n_dependants     int64
fam_status      object
income           int64
dtype: object

In [7]:
# Rename "Surnam" column
customers.rename(columns = {'Surnam' : 'Last Name'}, inplace = True)

In [8]:
# Get descriptive statistics
customers.describe()

             user_id            Age   n_dependants         income
count  206209.000000  206209.000000  206209.000000  206209.000000
mean   103105.000000      49.501646       1.499823   94632.852548
std     59527.555167      18.480962       1.118433   42473.786988
min         1.000000      18.000000       0.000000   25903.000000
25%     51553.000000      33.000000       0.000000   59874.000000
50%    103105.000000      49.000000       1.000000   93547.000000
75%    154657.000000      66.000000       3.000000  124244.000000
max    206209.000000      81.000000       3.000000  593901.000000

In [9]:
ords_prods_merged.dtypes

order_id                   int64
user_id                    int64
order_number               int64
orders_day_of_week         int64
order_hour_of_day          int64
days_since_last_order    float64
product_id                 int64
add_to_cart_order          int64
reordered                  int64
product_name              object
aisle_id                   int64
department_id              int64
prices                   float64
price_range_loc           object
busiest_days              object
busiest_period_of_day     object
max_order                  int64
loyalty_flag              object
avg_spent                float64
spending_flag             object
order_frequency          float64
frequency_flag            object
dtype: object

In [10]:
# Check for mixed-columns
for col in customers.columns.tolist():
   weird = (customers[[col]].applymap(type) != customers[[col]].iloc[0].apply(type)).any(axis = 1)
   if len (customers[weird]) > 0:
     print (col)

First Name

In [11]:
# Set "First Name" column to string
customers['First Name'] = customers['First Name'].astype('str')

In [12]:
# Search for missing values
customers.isnull().sum()

user_id         0
First Name      0
Last Name       0
Gender          0
STATE           0
Age             0
date_joined     0
n_dependants    0
fam_status      0
income          0
dtype: int64

In [13]:
# Search for duplicates
customers_dup = customers[customers.duplicated()]
customers_dup

Empty DataFrame
Columns: [user_id, First Name, Last Name, Gender, STATE, Age, date_joined, n_dependants, fam_status, income]
Index: []

In [14]:
# Value count of "First Name"
customers['First Name'].value_counts(dropna = False)

nan            11259
Marilyn         2213
Barbara         2154
Todd            2113
Jeremy          2104
Cynthia         1951
Rose            1880
Kathy           1863
Steven          1844
Sarah           1840
Irene           1823
Andrea          1698
Justin          1684
Bobby           1664
Clarence        1663
Harry           1638
Alice           1629
Ruby            1622
Julie           1607
Gloria          1590
Carl            1565
Shawn           1500
Gregory         1486
Brandon         1485
Frank           1482
Thomas          1480
Marie           1467
Robin           1463
Scott           1459
Robert          1450
Russell         1448
Linda           1433
Michael         1427
Peter           1417
Harold          1409
Ruth            1399
Jerry           1393
James           1367
Brenda          1306
Stephen         1300
Ralph           1290
Henry           1272
Mary            1263
Kenneth         1262
Victor          1260
Lois            1253
Deborah         1251
Bonnie          1249
Shirley         1242
Randy           1242
Debra           1241
Albert          1240
Ann             1239
Terry           1234
Beverly         1229
Amanda          1226
Lillian         1225
Kimberly        1214
Janice          1213
Ernest          1208
Lisa            1205
Patricia        1201
Gerald          1198
Jonathan        1197
Roger           1193
Maria           1184
Sharon          1109
Amy             1083
Denise          1079
Elizabeth       1077
Kevin           1075
Joseph          1074
Ashley          1072
Louise          1066
Anne            1062
Joe             1059
Jane            1051
Johnny          1047
Kathryn         1046
Diana           1045
Tina            1040
Sara            1037
Phyllis         1037
Stephanie       1036
Rebecca         1035
Benjamin        1034
Steve           1032
Willie          1031
Jacqueline      1028
Kathleen        1027
Judy            1025
Craig           1023
Charles         1020
John            1020
Christopher     1018
Cheryl          1017
Walter          1010
Jason           1002
Mark            1001
Matthew          998
Sean             989
Katherine        987
Douglas          976
Frances          961
Jessica          895
Antonio          868
Christine        867
Patrick          866
Teresa           855
Doris            846
Phillip          844
Nancy            841
Larry            838
Philip           834
Lawrence         832
Carlos           831
Sandra           830
Nicole           827
Ryan             821
Billy            817
George           817
Margaret         816
Joshua           815
Adam             811
Evelyn           811
Annie            810
Wayne            807
Bruce            802
Aaron            800
Arthur           796
Samuel           795
Theresa          785
Fred             784
Diane            756
Edward           755
Rachel           749
Karen            673
Judith           670
Jesse            653
Laura            652
Catherine        645
Jeffrey          645
Earl             642
Jennifer         641
Alan             641
Anthony          639
Ronald           633
Christina        632
Jack             631
Lori             630
Susan            625
Louis            624
Carolyn          622
Melissa          622
Daniel           619
Roy              619
Helen            618
Jimmy            615
Emily            615
Gary             612
Donald           608
Raymond          606
William          605
Norma            603
Donna            593
Michelle         593
Paul             591
Joyce            591
Betty            589
Nicholas         585
Richard          585
Virginia         578
Howard           578
Kelly            437
Jose             436
Paula            432
Dorothy          429
Chris            425
Julia            424
Joan             422
Andrew           420
Mildred          419
Heather          419
Anna             417
Eric             416
Martin           415
Janet            395
Timothy          392
Wanda            392
Juan             389
Martha           370
Pamela           357
Major            232
Angela           230
Dennis           229
Brian            220
Bob              215
Tom              213
Roberto          212
Jean             211
Carol            209
Keith            198
Tammy            198
Merry            197
Eugene           197
Garry            191
David            186
Ned              186
Name: First Name, dtype: int64

##### No values were blank, but there are an awful lot that were filled in as "nan." I won't take any action, as it is extremely unlikely that any further analysis will require first names in order to be relevant.

In [15]:
# Value count of "Last Name"
customers['Last Name'].value_counts(dropna = False)

Hamilton       252
Randall        248
Pennington     243
Lamb           243
Barnett        242
Ward           241
Walton         241
Kline          239
Berry          239
Berg           239
Mccoy          238
Buchanan       237
Morris         237
Jackson        236
Mitchell       236
Dickson        236
Fischer        236
Medrano        236
Johnson        235
Bass           235
Barber         235
Quinn          234
Trejo          234
Golden         234
Maynard        234
Browning       234
Cochran        233
Hubbard        233
Ware           233
Mcdaniel       233
Hill           232
Marin          232
Le             232
Gonzalez       232
Waters         232
Williamson     232
Duarte         232
Tang           232
Bean           231
Marquez        231
Robbins        231
Wise           231
May            231
Bradley        231
Koch           231
Christensen    231
Carlson        230
Hurley         230
Rodriguez      230
Garcia         229
Conway         229
Wilcox         229
Kirby          229
Xiong          229
Khan           229
Flynn          229
Bowman         229
Wallace        229
Lowery         228
Kirk           228
Lucas          228
Shah           228
Shelton        228
Buck           228
Velazquez      228
Carson         228
Mcintyre       227
Petersen       227
Dorsey         227
Mayo           227
Brady          227
Webb           227
Harrington     227
Rosales        227
Dickerson      227
Maldonado      226
Weiss          226
Shaffer        226
Deleon         226
Pena           226
Rocha          226
Simmons        226
Arnold         226
Bruce          226
Schaefer       225
Stephenson     225
Medina         225
Henson         225
Ryan           225
Esquivel       225
Orozco         225
Fisher         225
Adkins         225
Bernard        225
Nash           225
Hudson         225
Mercado        224
Richard        224
Pugh           224
Bridges        224
Mayer          224
Stewart        224
Macias         224
Bradford       224
Garner         224
Valdez         224
Lawson         224
Reed           224
Gaines         224
Andrade        224
Gibbs          224
Duran          223
Carter         223
Rios           223
Shields        223
Dudley         223
Romero         223
Walls          223
Hogan          223
Morgan         223
Castro         223
Gallegos       223
Mcdonald       223
Long           223
Fox            223
Cano           223
Graves         223
Burke          223
Barnes         223
Berger         223
Hancock        223
Blackburn      223
Morse          223
Coffey         222
Johns          222
Oconnell       222
Murillo        222
Brandt         222
Herrera        222
Ortega         222
Robinson       222
Weaver         222
Sandoval       222
Chang          222
Rivers         221
Arroyo         221
Lloyd          221
Harrison       221
Allison        221
Chambers       221
Schultz        221
Herring        221
Gallagher      221
Huff           221
Owen           221
Lewis          221
Nunez          220
Oneill         220
Barajas        220
Watts          220
Aguilar        220
Enriquez       220
Carpenter      220
Durham         220
Neal           220
Compton        220
Vu             220
Everett        220
Morton         220
Pollard        220
Nielsen        220
Baldwin        220
Landry         220
Fowler         220
Lam            220
Tapia          220
Ellis          220
Stanton        220
Whitehead      219
Ayers          219
Maxwell        219
Mcbride        219
Ponce          219
Holt           219
Phan           219
Wall           219
Choi           219
Keller         219
Patel          219
Cisneros       219
Zuniga         219
Lee            219
Burton         219
David          219
Mejia          219
Yu             219
Callahan       219
Cain           219
Schmitt        219
Cantrell       219
Simon          219
Knight         219
Washington     218
Lu             218
Snyder         218
Moses          218
Yates          218
Parker         218
Vargas         218
Howe           218
Gutierrez      218
Vasquez        218
Norton         218
Harmon         218
Palmer         218
Reyes          218
Salinas        218
Peterson       218
Oneal          218
Sosa           218
Gould          217
Small          217
Shannon        217
Martin         217
Sherman        217
Bennett        217
Taylor         217
Cordova        217
Juarez         217
Oconnor        217
Hobbs          217
Boyd           217
Roth           217
Case           217
Diaz           217
Peck           217
Leonard        217
Jaramillo      217
Higgins        217
Dillon         217
Montoya        217
Snow           217
Galvan         216
Webster        216
James          216
Pacheco        216
Morales        216
Hall           216
Galindo        216
Keith          216
Cannon         216
Willis         216
Cox            216
Conley         216
Melendez       216
Meyer          216
Zimmerman      216
Wright         216
Glenn          216
Sanchez        216
Vo             216
Barron         216
Holloway       216
Boyle          216
Cooper         216
Branch         215
Grimes         215
Farrell        215
Friedman       215
Love           215
Richmond       215
Faulkner       215
Jenkins        215
Sutton         215
Espinoza       215
Mcintosh       215
Beasley        215
Williams       215
Day            215
Booker         215
Summers        215
Robertson      215
Rubio          215
Tate           214
Maddox         214
Barrera        214
Newton         214
Cortes         214
Ramos          214
Byrd           214
Mahoney        214
Jensen         214
Curry          214
Ball           214
Welch          214
Kelley         214
Hail           214
Wilkins        214
Spears         214
Yang           214
Odom           214
Kim            213
Gilbert        213
Wolf           213
Parks          213
Mata           213
Booth          213
Charles        213
Villegas       213
White          213
Greer          213
Gibson         213
Schroeder      213
Cabrera        213
Portillo       213
Turner         213
Kennedy        213
Costa          213
Newman         213
Potter         213
Zavala         213
Castaneda      213
Barr           213
Walter         213
Calderon       213
Edwards        213
Boone          213
Holland        213
Zhang          213
Foley          213
Flores         213
Goodman        213
Navarro        212
Chandler       212
Grant          212
Reeves         212
Blair          212
Pitts          212
Mack           212
Patton         212
Robles         212
French         212
Hardy          212
Corona         212
Haley          212
Estrada        212
Dominguez      212
Mendoza        212
Sweeney        211
Cross          211
Noble          211
Wagner         211
Horton         211
Lynch          211
Oliver         211
Bautista       211
Meyers         211
Pineda         211
Leon           211
Kemp           211
Hull           211
Luna           211
Delacruz       211
Floyd          211
Best           211
Gray           211
Price          211
Vega           211
Wiley          211
Livingston     211
Stout          211
Benitez        211
Merritt        211
Carrillo       211
Cantu          211
King           211
Aguirre        211
Marshall       211
Cohen          211
Valentine      210
Tyler          210
Vance          210
Clark          210
Hardin         210
Carroll        210
Hanson         210
Dodson         210
Lucero         210
Heath          210
Delarosa       210
Potts          210
Good           210
Brennan        210
Rowland        210
Beard          210
Burch          210
Trevino        210
Kramer         210
Whitney        210
Fitzpatrick    210
Rhodes         210
Riley          210
Short          210
Camacho        210
Dejesus        210
Bravo          209
Paul           209
Soto           209
Bryan          209
Gillespie      209
Schneider      209
Solis          209
Ford           209
Conrad         209
Hendrix        209
House          209
Esparza        209
Clements       209
Allen          209
Hendricks      209
Woods          209
Patterson      209
Daniel         209
Lester         209
Vazquez        209
Bond           209
Rosario        209
Evans          209
Villa          209
Stephens       209
Mendez         209
Knapp          208
Becker         208
Marsh          208
Meadows        208
Davidson       208
Terrell        208
Obrien         208
Herman         208
Frazier        208
Stuart         208
Ochoa          208
Cameron        208
Figueroa       208
Fry            208
Wheeler        208
Logan          208
Crane          208
Russell        208
Buckley        208
Frank          208
Rojas          208
Church         208
Kane           208
Lynn           208
Delgado        208
Rosas          208
Russo          208
Hunt           208
Eaton          207
Curtis         207
Burnett        207
Hickman        207
Lane           207
Avalos         207
York           207
Perry          207
Truong         207
Humphrey       207
Fletcher       207
Chen           207
Griffith       207
Melton         207
Schwartz       207
West           207
Santiago       207
Leach          207
Hinton         207
Valencia       207
Mcgee          207
Powers         207
Howell         207
Mccann         207
Garrett        207
Castillo       206
Massey         206
Tanner         206
Dyer           206
Donaldson      206
Huffman        206
Ross           206
Caldwell       206
Chavez         206
Mclaughlin     206
Norman         206
Griffin        206
Villarreal     206
Sparks         206
Macdonald      206
Blanchard      206
Nelson         206
Roman          206
Beck           206
Lindsey        206
Thomas         206
Nolan          206
Dixon          206
Myers          206
Palacios       206
Lawrence       205
Mcpherson      205
Salazar        205
Hanna          205
Chase          205
Raymond        205
Bell           205
Spence         205
Combs          205
Norris         205
Villalobos     205
Mckinney       205
Osborne        205
Nichols        205
Harding        205
Acevedo        205
Strong         205
Hernandez      205
Montgomery     205
Hansen         205
Santos         205
Terry          205
Henry          205
Mclean         205
Cunningham     205
Alexander      205
Cortez         205
Bowen          205
Little         205
Butler         205
Lang           205
Walters        205
Ahmed          205
Beil           205
Leal           205
Rose           205
Santana        204
Yoder          204
Wilkinson      204
Guzman         204
Whitaker       204
Dalton         204
Warren         204
Calhoun        204
Thompson       204
Moss           204
Zamora         204
Adams          204
Erickson       204
Gilmore        204
Mcclure        204
Davenport      204
Silva          204
Hines          204
Stokes         204
Mccall         204
Rivas          204
Bowers         204
Prince         204
Steele         204
Rowe           203
Coleman        203
Phelps         203
Benton         203
Tucker         203
Townsend       203
Mueller        203
Levy           203
Benjamin       203
Mckee          203
Parrish        203
Cline          203
Mullen         203
Quintana       203
Franco         203
Sierra         203
Francis        203
Thornton       203
Crawford       203
Fuentes        203
Gordon         203
Mays           203
Fitzgerald     203
Barton         203
Mcconnell      203
Mcfarland      202
Waller         202
Gentry         202
Garrison       202
Mullins        202
Cervantes      202
Klein          202
Salgado        202
Mcdowell       202
Larson         202
Ellison        202
Frost          202
Glover         202
Velez          202
Underwood      202
Shaw           202
Stein          202
Estes          202
Hoover         202
Bartlett       202
Parra          202
Crosby         202
Hebert         202
Wells          202
Hayes          202
Wiggins        202
Padilla        202
Austin         202
Montes         202
Franklin       202
Stanley        201
Anthony        201
Campbell       201
Anderson       201
Matthews       201
Lin            201
Lambert        201
Bernal         201
Collins        201
Clarke         201
Fuller         201
Giles          201
Andrews        201
Arias          201
Glass          201
Porter         201
Suarez         201
Wu             201
Chapman        201
Sanders        201
Moore          201
Gates          201
Moreno         201
Horne          201
Valenzuela     201
Alfaro         201
Pope           201
Richardson     200
Singh          200
Huber          200
Sampson        200
Atkins         200
Rodgers        200
Fleming        200
Flowers        200
Manning        200
Tran           200
Randolph       200
Mcmillan       200
Wong           200
Liu            200
Olsen          200
Daugherty      200
Sharp          200
Parsons        200
Jacobs         200
Mills          199
Marks          199
Mccarthy       199
Harris         199
Brewer         199
Farmer         199
Moody          199
English        199
Larsen         199
Pruitt         199
Jefferson      199
Dougherty      199
Page           199
Strickland     199
Ali            199
Stevenson      199
Hensley        199
Lugo           199
Owens          199
Todd           198
Fernandez      198
Ho             198
Burgess        198
Vincent        198
Wood           198
Graham         198
Harper         198
Bentley        198
Bailey         198
Vang           198
Nixon          198
Greene         198
Madden         198
Quintero       198
Roberson       198
Mckenzie       198
Guevara        198
Holmes         198
Harvey         198
Douglas        198
Frederick      198
Banks          198
Murray         198
Rogers         198
Sims           198
Simpson        198
Skinner        198
Mccullough     198
Guerra         198
Farley         197
Shepherd       197
Donovan        197
Torres         197
Johnston       197
Alvarado       197
Middleton      197
Ibarra         197
Mcmahon        197
Person         197
Jimenez        197
Brooks         197
Monroe         197
Sawyer         197
Davis          197
Hodges         197
Krueger        197
Preston        197
Jarvis         197
Munoz          197
Mann           197
Reese          197
Lyons          196
Green          196
Roy            196
Dunn           196
Ballard        196
Novak          196
Savage         196
Harrell        196
Hunter         196
Odonnell       196
Pierce         196
Baxter         196
Rasmussen      196
Young          196
Kelly          196
Gomez          196
Pace           196
Clay           196
Jacobson       196
Wade           196
Wolfe          196
Lara           195
Hodge          195
Rollins        195
Collier        195
Blankenship    195
Hart           195
Dawson         195
Dean           195
Drake          195
Colon          195
Cook           195
Hale           195
Reynolds       195
Hoffman        195
Wilkerson      195
Campos         195
Pittman        195
Blevins        195
Armstrong      195
Peters         195
Gill           195
Bishop         195
Hester         195
Kerr           195
Scott          194
Morrow         194
Morrison       194
Huang          194
Cummings       194
Carey          194
Moon           194
Ray            194
Murphy         194
Espinosa       194
Burns          194
Contreras      194
Meza           194
Ramsey         194
Hutchinson     194
Shepard        194
Vaughn         194
Miller         194
Sanford        194
Rice           194
Kaur           194
Schmidt        194
Mora           194
Horn           194
Sellers        193
Mosley         193
Stafford       193
Malone         193
Rich           193
Lozano         193
Richards       193
Blackwell      193
Warner         193
Velasquez      193
Kent           193
Bonilla        193
Christian      193
Frye           193
Bradshaw       193
Gardner        193
Felix          193
Blake          193
Baker          192
Barry          192
Wang           192
Woodward       192
Bryant         192
Powell         192
Cardenas       192
Correa         192
Sullivan       192
Salas          192
Ayala          192
Rangel         192
Hampton        192
Vaughan        192
Roach          192
Ferguson       192
Guerrero       192
George         192
Hood           192
Gregory        192
Clayton        191
Cherry         191
Moyer          191
Phillips       191
Jones          191
Nguyen         191
Casey          191
Ingram         191
Decker         191
Bush           191
Dunlap         191
Freeman        191
Travis         191
Alvarez        191
Watkins        191
Chung          191
Davila         191
Avery          191
Olson          191
Villanueva     191
Beltran        191
Huerta         190
Patrick        190
Gonzales       190
Finley         190
Hammond        190
Fields         190
Arellano       190
Bender         190
Moran          190
Sheppard       190
Brock          190
Barker         190
Ventura        190
Howard         190
Ortiz          190
Barrett        190
Michael        190
Bullock        190
Lim            189
Winters        189
Walsh          189
Benson         189
Solomon        189
Abbott         189
Escobar        189
Ruiz           189
Peralta        189
Trujillo       189
Sexton         189
Doyle          189
Proctor        189
Andersen       189
Mathews        189
Sloan          189
Miranda        188
Walker         188
Pham           188
Henderson      188
Li             188
Hayden         188
Rivera         188
Garza          188
Lowe           188
Stone          188
Stevens        188
Singleton      188
Hawkins        188
Wyatt          188
Mccormick      188
Hughes         188
Knox           188
Molina         188
Cole           187
Watson         187
Cruz           187
Duffy          187
Mckay          187
Mcguire        187
Ramirez        187
Reyna          187
Spencer        187
Nava           187
Duke           187
Atkinson       186
Magana         186
Pratt          186
Reid           186
Carr           186
Cuevas         186
Woodard        186
Briggs         186
Stark          186
Foster         186
Lopez          186
Hicks          185
Ashley         185
Haynes         185
Acosta         185
Joseph         185
Hess           185
Goodwin        185
Cobb           185
Roberts        184
Mcclain        184
Hopkins        183
Copeland       183
Orr            183
Rush           183
Jennings       183
Reilly         183
Miles          183
Perez          183
Mathis         182
Dennis         182
Avila          182
Daniels        182
Weber          181
Bates          181
Leblanc        181
Duncan         181
Houston        181
Chan           181
Nicholson      181
Conner         180
Craig          180
Swanson        180
Elliott        180
Hahn           180
Huynh          179
Black          179
Smith          179
Perkins        179
Archer         178
Martinez       178
Gross          177
Wilson         177
Hartman        177
Weeks          176
Park           175
Saunders       175
Hurst          174
Brown          174
Serrano        173
Boyer          173
Mason          173
Mccarty        173
Poole          172
Bauer          166
Pearson        164
Payne          163
Jordan         162
Name: Last Name, dtype: int64

In [16]:
# Value count of "Gender"
customers['Gender'].value_counts(dropna = False)

Male      104067
Female    102142
Name: Gender, dtype: int64

In [17]:
# Value count of "STATE"
customers['STATE'].value_counts(dropna = False)

Delaware                4044
Connecticut             4044
Arkansas                4044
Indiana                 4044
Alabama                 4044
Alaska                  4044
Hawaii                  4044
Iowa                    4044
Colorado                4044
Arizona                 4044
Georgia                 4044
California              4044
District of Columbia    4044
Idaho                   4044
Florida                 4044
Illinois                4044
Washington              4043
Utah                    4043
New York                4043
Rhode Island            4043
Wyoming                 4043
West Virginia           4043
New Mexico              4043
Oklahoma                4043
Vermont                 4043
South Carolina          4043
New Hampshire           4043
Louisiana               4043
Wisconsin               4043
North Carolina          4043
Maine                   4043
Nebraska                4043
Nevada                  4043
North Dakota            4043
Tennessee               4043
Oregon                  4043
Minnesota               4043
Michigan                4043
Kentucky                4043
Kansas                  4043
South Dakota            4043
Missouri                4043
Pennsylvania            4043
Maryland                4043
Mississippi             4043
Virginia                4043
Texas                   4043
New Jersey              4043
Massachusetts           4043
Ohio                    4043
Montana                 4043
Name: STATE, dtype: int64

In [18]:
# Value count of "date_joined"
customers['date_joined'].value_counts(dropna = False)

9/17/2018     213
2/10/2018     212
4/1/2019      211
9/21/2019     211
12/19/2017    210
12/24/2019    209
11/19/2019    205
10/11/2017    205
1/7/2018      205
1/25/2019     205
12/6/2019     204
9/30/2019     203
3/26/2018     203
3/31/2019     203
10/18/2019    203
7/28/2018     203
3/12/2020     202
10/20/2018    202
10/17/2019    202
11/21/2018    202
3/23/2018     202
3/2/2020      202
11/6/2018     202
10/6/2018     202
3/8/2019      201
10/18/2017    201
2/1/2017      201
12/28/2018    201
5/4/2018      201
11/14/2017    200
5/11/2018     200
1/19/2017     200
7/23/2018     200
8/10/2017     199
4/13/2019     199
4/7/2018      199
1/23/2018     199
10/23/2018    198
12/25/2017    198
9/28/2019     198
3/10/2017     198
7/20/2017     198
5/13/2019     198
7/7/2018      198
9/12/2017     198
3/28/2020     197
7/21/2018     197
11/12/2018    197
8/4/2017      197
2/1/2018      197
8/13/2018     197
5/18/2019     197
1/12/2017     197
12/18/2018    196
6/4/2019      196
9/30/2017     196
9/24/2017     196
4/4/2017      196
3/5/2020      196
11/16/2019    196
8/8/2019      195
11/28/2017    195
11/18/2019    195
4/21/2017     195
8/14/2017     195
9/28/2017     195
10/8/2018     195
3/16/2017     195
8/4/2019      195
5/2/2018      195
1/8/2020      195
9/2/2019      195
6/7/2019      194
2/6/2017      194
2/16/2018     194
9/10/2017     194
2/29/2020     194
12/22/2018    194
2/3/2019      193
5/28/2018     193
10/10/2018    193
2/9/2020      193
6/13/2019     193
2/24/2020     193
2/3/2017      193
2/8/2018      193
1/9/2019      192
2/10/2017     192
10/10/2017    192
6/20/2017     192
7/16/2019     192
5/1/2019      192
4/2/2019      192
10/5/2017     192
5/25/2019     192
7/4/2017      192
1/10/2017     192
6/3/2018      191
9/6/2018      191
3/19/2018     191
2/22/2019     191
3/16/2020     191
3/28/2017     191
2/14/2020     191
2/17/2020     191
4/5/2017      191
11/7/2017     191
5/31/2017     191
9/13/2017     191
8/25/2017     191
10/30/2017    190
8/26/2019     190
1/3/2018      190
4/29/2019     190
3/28/2018     190
12/31/2017    190
10/21/2017    190
8/18/2017     190
2/19/2017     190
3/25/2017     190
2/4/2017      190
8/20/2018     190
5/10/2018     190
2/16/2017     190
3/13/2018     190
4/6/2019      190
7/23/2019     190
12/1/2017     190
4/26/2018     189
1/21/2018     189
12/7/2017     189
5/14/2018     189
3/19/2020     189
8/9/2017      189
4/2/2018      189
6/8/2017      189
11/16/2017    189
7/16/2017     189
6/30/2018     189
12/11/2017    189
2/5/2018      189
6/21/2017     189
10/14/2018    188
3/11/2018     188
2/13/2020     188
4/15/2017     188
11/5/2019     188
10/4/2019     188
12/30/2019    188
2/20/2018     188
12/19/2018    188
8/23/2017     188
1/2/2019      188
8/12/2018     188
1/4/2017      188
9/1/2019      188
8/24/2019     188
10/21/2019    187
10/2/2019     187
7/17/2018     187
12/20/2018    187
8/4/2018      187
10/13/2019    187
7/25/2018     187
8/19/2017     187
4/9/2018      187
1/23/2019     187
12/4/2017     187
7/31/2019     187
3/6/2017      187
11/20/2017    187
5/28/2019     187
1/12/2020     187
12/9/2017     187
3/6/2019      187
1/20/2018     187
1/24/2019     187
3/9/2019      187
1/24/2017     187
8/10/2019     187
10/29/2019    187
8/16/2019     186
6/1/2017      186
5/3/2018      186
5/29/2019     186
4/7/2019      186
2/2/2017      186
11/10/2017    186
9/6/2017      186
2/3/2018      186
7/22/2018     186
9/16/2017     186
4/19/2018     186
1/26/2018     186
8/20/2017     186
9/28/2018     186
12/27/2018    186
11/24/2019    186
1/11/2018     186
4/5/2018      186
10/19/2017    186
1/15/2017     186
3/1/2020      186
3/8/2017      186
5/26/2019     186
7/6/2017      186
9/15/2017     186
3/6/2020      186
12/21/2017    186
9/9/2017      186
12/7/2018     186
8/11/2019     186
9/14/2017     185
2/19/2020     185
9/10/2019     185
10/20/2017    185
11/22/2017    185
6/26/2018     185
8/19/2018     185
1/27/2018     185
7/5/2019      185
10/30/2018    185
2/27/2018     185
1/12/2019     185
8/24/2017     185
3/24/2017     185
3/13/2020     185
8/26/2018     185
7/30/2017     185
1/7/2020      185
8/27/2019     185
6/8/2019      185
9/29/2018     185
3/3/2017      185
5/28/2017     185
1/30/2019     185
3/1/2017      184
3/5/2018      184
1/18/2017     184
1/23/2020     184
3/25/2019     184
2/20/2019     184
8/6/2019      184
6/15/2017     184
2/25/2018     184
8/15/2018     184
9/3/2017      184
8/23/2019     184
2/19/2019     184
6/17/2018     184
4/11/2018     184
4/21/2019     184
5/4/2017      184
6/28/2018     184
5/3/2019      184
1/22/2020     184
9/6/2019      183
5/15/2017     183
8/27/2017     183
1/26/2019     183
2/9/2019      183
8/5/2019      183
6/2/2019      183
11/10/2019    183
9/24/2018     183
6/2/2018      183
7/6/2019      183
9/26/2018     183
1/22/2017     183
3/7/2019      183
2/23/2020     183
9/21/2017     183
6/20/2018     183
11/4/2018     183
8/7/2017      183
5/14/2019     183
10/11/2019    183
6/26/2017     183
11/20/2018    183
10/24/2017    183
9/19/2018     183
5/12/2017     183
4/20/2018     183
3/13/2019     183
1/26/2020     183
5/19/2017     183
7/30/2019     183
3/10/2020     183
9/1/2017      183
11/7/2019     183
2/12/2019     183
8/6/2017      183
6/25/2018     182
7/26/2017     182
4/18/2017     182
11/1/2019     182
8/15/2019     182
8/2/2019      182
7/27/2017     182
4/30/2017     182
10/5/2018     182
2/3/2020      182
6/10/2018     182
12/12/2017    182
10/4/2017     182
6/4/2018      182
3/20/2018     182
1/2/2018      182
4/30/2018     182
11/2/2018     182
2/28/2018     182
3/31/2017     182
4/23/2017     182
5/11/2017     182
9/9/2019      181
3/18/2019     181
10/31/2018    181
3/6/2018      181
8/9/2019      181
5/23/2018     181
9/3/2018      181
6/21/2019     181
11/25/2018    181
1/6/2018      181
1/20/2017     181
4/16/2017     181
12/23/2019    181
6/18/2017     181
6/12/2018     181
7/26/2019     181
7/27/2018     181
4/19/2019     181
8/25/2019     181
4/6/2018      181
12/2/2017     181
3/2/2018      181
1/17/2020     181
9/5/2019      181
7/1/2019      181
1/3/2020      181
10/23/2017    181
8/30/2017     181
6/23/2018     181
4/12/2017     181
4/10/2018     181
5/2/2017      181
3/17/2017     181
3/20/2020     181
7/24/2019     181
7/10/2019     181
10/15/2017    181
8/17/2019     181
7/3/2019      181
11/21/2017    181
12/25/2019    180
9/7/2017      180
4/26/2017     180
10/1/2017     180
9/25/2019     180
3/7/2020      180
5/24/2018     180
11/27/2019    180
11/23/2019    180
2/24/2018     180
11/17/2017    180
4/16/2019     180
12/2/2018     180
1/27/2020     180
12/17/2019    180
12/3/2019     180
6/11/2017     180
9/18/2019     180
5/30/2018     180
8/3/2017      180
3/4/2018      180
10/7/2017     180
5/16/2017     180
4/4/2018      180
12/5/2017     180
4/12/2019     180
2/6/2019      180
4/11/2017     180
7/24/2018     180
4/3/2018      180
6/25/2019     180
12/29/2018    180
12/10/2017    180
2/1/2020      180
2/12/2020     179
1/21/2017     179
7/22/2017     179
4/17/2019     179
4/28/2018     179
12/19/2019    179
12/16/2019    179
4/29/2018     179
7/31/2017     179
5/20/2018     179
4/1/2017      179
8/13/2017     179
10/29/2018    179
6/5/2018      179
6/8/2018      179
11/8/2019     179
4/28/2019     179
3/4/2019      179
9/27/2019     179
3/26/2020     179
2/4/2019      179
11/28/2018    179
8/11/2017     179
2/13/2017     179
2/22/2017     179
3/15/2020     178
7/30/2018     178
1/13/2018     178
1/4/2019      178
9/27/2018     178
5/1/2017      178
6/24/2017     178
5/23/2017     178
12/20/2019    178
5/5/2017      178
2/18/2020     178
12/28/2017    178
10/21/2018    178
2/7/2020      178
1/22/2019     178
3/7/2017      178
6/30/2017     178
5/16/2018     178
2/6/2018      178
8/28/2017     178
10/5/2019     178
10/8/2017     178
3/1/2018      178
8/16/2018     178
7/15/2017     178
8/29/2017     178
8/3/2019      178
6/13/2017     178
2/20/2020     178
4/4/2019      177
4/18/2019     177
6/14/2019     177
8/30/2019     177
10/12/2018    177
4/20/2019     177
4/14/2018     177
8/21/2019     177
2/14/2019     177
4/21/2018     177
2/11/2020     177
3/11/2019     177
6/28/2017     177
10/12/2017    177
2/17/2019     177
8/14/2019     177
6/1/2019      177
8/13/2019     177
3/8/2020      177
9/21/2018     177
2/8/2017      177
5/29/2018     177
7/17/2017     177
9/2/2018      177
2/5/2017      177
10/7/2019     177
8/15/2017     177
2/26/2019     177
2/22/2018     177
5/11/2019     177
2/19/2018     177
6/20/2019     177
7/11/2019     177
3/21/2017     177
2/21/2020     177
1/5/2017      177
4/13/2018     177
1/7/2017      177
12/4/2018     176
5/9/2018      176
3/30/2019     176
10/23/2019    176
3/19/2019     176
1/8/2017      176
1/10/2019     176
3/10/2019     176
11/16/2018    176
3/22/2020     176
6/22/2018     176
6/17/2019     176
2/4/2018      176
2/8/2020      176
4/20/2017     176
11/13/2019    176
8/1/2017      176
9/14/2018     176
10/19/2018    176
10/22/2017    176
10/28/2018    176
3/22/2018     176
5/17/2019     176
10/30/2019    176
1/21/2019     176
12/10/2018    176
3/17/2020     176
5/30/2017     176
12/20/2017    176
9/17/2019     176
1/14/2019     176
10/27/2017    176
2/25/2017     176
10/28/2019    176
2/4/2020      176
3/23/2020     176
5/21/2017     176
10/20/2019    175
9/19/2019     175
3/3/2018      175
6/3/2017      175
2/7/2018      175
9/23/2019     175
1/19/2020     175
7/14/2018     175
4/11/2019     175
12/30/2018    175
9/22/2017     175
11/15/2019    175
4/2/2017      175
1/3/2019      175
4/25/2018     175
4/10/2019     175
3/23/2019     175
5/27/2019     175
10/15/2018    175
8/30/2018     175
3/29/2017     175
10/3/2017     175
5/27/2018     175
9/19/2017     175
11/30/2019    175
4/15/2018     175
11/2/2019     175
3/13/2017     175
6/16/2019     175
5/19/2018     175
5/26/2018     175
11/15/2017    175
12/24/2017    175
2/17/2018     175
12/31/2019    175
8/12/2019     175
12/14/2018    175
6/22/2017     175
10/24/2019    175
6/23/2017     175
3/4/2017      175
12/7/2019     175
8/23/2018     175
6/3/2019      175
12/16/2018    175
6/10/2017     175
6/6/2018      174
12/2/2019     174
1/5/2019      174
3/12/2017     174
10/8/2019     174
2/23/2019     174
5/9/2017      174
5/26/2017     174
5/20/2017     174
10/18/2018    174
10/2/2017     174
3/22/2019     174
11/12/2017    174
10/12/2019    174
9/11/2017     174
5/10/2019     174
7/29/2019     174
12/29/2019    174
6/6/2017      174
3/3/2019      174
4/23/2019     174
1/13/2019     174
10/1/2019     174
1/31/2018     174
5/18/2018     174
11/9/2018     174
11/17/2018    174
1/19/2019     174
7/5/2018      174
1/13/2017     174
5/6/2018      174
12/17/2018    174
1/25/2018     174
7/3/2017      174
7/31/2018     174
6/7/2018      174
4/1/2018      174
9/9/2018      174
9/25/2018     173
8/18/2018     173
12/26/2017    173
5/18/2017     173
9/12/2018     173
12/10/2019    173
11/27/2018    173
11/23/2018    173
1/31/2020     173
1/20/2019     173
2/1/2019      173
5/8/2018      173
7/24/2017     173
11/5/2017     173
6/5/2017      173
3/8/2018      173
1/9/2018      173
12/8/2017     173
1/30/2017     173
4/22/2019     173
3/4/2020      173
5/21/2018     173
9/11/2018     173
10/22/2019    173
1/17/2017     173
7/18/2017     173
4/3/2019      173
4/24/2018     173
9/10/2018     173
9/4/2019      173
6/19/2019     173
10/3/2019     173
1/8/2018      173
12/4/2019     173
4/8/2019      173
1/31/2019     173
2/26/2020     173
1/5/2018      173
8/28/2018     172
7/2/2018      172
11/22/2019    172
4/27/2018     172
8/3/2018      172
3/17/2018     172
4/9/2019      172
11/19/2018    172
3/25/2018     172
1/6/2017      172
6/9/2019      172
9/20/2018     172
1/23/2017     172
5/9/2019      172
3/24/2020     172
12/1/2018     172
4/10/2017     172
6/4/2017      172
5/7/2018      172
4/14/2019     172
5/3/2017      172
4/8/2017      172
8/5/2017      172
11/28/2019    172
7/29/2017     172
8/18/2019     172
4/24/2019     172
7/8/2018      172
7/12/2017     172
9/25/2017     172
10/6/2019     172
7/10/2018     172
3/14/2019     172
4/27/2019     171
7/10/2017     171
1/18/2019     171
8/19/2019     171
2/12/2017     171
1/27/2017     171
7/19/2017     171
10/25/2019    171
8/22/2018     171
3/29/2020     171
5/7/2019      171
9/22/2019     171
5/14/2017     171
9/26/2019     171
11/14/2019    171
5/22/2019     171
5/22/2018     171
4/19/2017     171
9/12/2019     171
5/25/2017     171
11/29/2019    171
1/17/2018     171
2/13/2018     171
3/12/2018     171
8/11/2018     171
8/20/2019     171
3/21/2020     171
1/9/2017      171
10/17/2017    171
4/17/2017     171
12/22/2017    171
6/5/2019      171
1/13/2020     170
10/9/2018     170
6/30/2019     170
3/17/2019     170
7/2/2019      170
10/27/2018    170
2/6/2020      170
7/18/2018     170
5/17/2017     170
4/22/2018     170
6/1/2018      170
5/6/2017      170
3/11/2020     170
2/10/2020     170
12/8/2019     170
10/10/2019    170
1/14/2018     170
3/28/2019     170
12/23/2017    170
2/28/2019     170
3/3/2020      170
7/2/2017      170
5/31/2019     170
12/26/2019    170
7/17/2019     170
8/5/2018      170
8/2/2018      170
1/16/2018     170
1/25/2020     170
1/16/2020     170
10/16/2019    170
5/27/2017     170
2/5/2019      170
8/7/2019      170
3/19/2017     170
9/27/2017     170
2/13/2019     170
6/27/2019     170
3/14/2018     169
11/3/2017     169
11/30/2018    169
2/24/2017     169
3/21/2018     169
3/9/2020      169
8/31/2018     169
1/3/2017      169
4/7/2017      169
12/23/2018    169
2/16/2019     169
6/16/2018     169
5/6/2019      169
7/28/2019     169
12/11/2018    169
6/28/2019     169
9/4/2017      169
8/25/2018     169
5/13/2017     169
3/7/2018      169
5/2/2019      169
12/22/2019    169
8/14/2018     169
3/12/2019     169
11/21/2019    169
10/24/2018    169
11/1/2018     169
4/1/2020      169
5/23/2019     169
3/15/2019     169
7/14/2019     169
7/11/2018     169
8/26/2017     169
1/4/2020      169
6/23/2019     169
2/28/2020     169
2/17/2017     169
6/16/2017     168
6/15/2019     168
12/9/2019     168
3/15/2017     168
11/5/2018     168
6/15/2018     168
1/7/2019      168
1/24/2018     168
2/2/2019      168
11/6/2019     168
12/21/2018    168
6/11/2019     168
1/11/2019     168
7/16/2018     168
11/1/2017     168
12/11/2019    168
1/28/2017     168
8/8/2017      168
12/13/2019    168
4/25/2019     168
6/14/2018     168
7/7/2017      168
6/18/2019     168
7/9/2019      168
5/12/2019     168
1/20/2020     168
2/14/2018     168
12/21/2019    168
4/13/2017     168
5/30/2019     168
3/20/2017     168
8/2/2017      168
6/11/2018     168
11/25/2019    168
2/12/2018     167
2/18/2017     167
11/23/2017    167
7/19/2019     167
10/3/2018     167
9/17/2017     167
7/1/2018      167
7/13/2018     167
10/19/2019    167
8/7/2018      167
12/5/2019     167
7/11/2017     167
1/4/2018      167
1/30/2018     167
11/11/2019    167
4/5/2019      167
3/11/2017     167
11/30/2017    167
10/27/2019    167
2/27/2017     167
12/13/2017    167
10/26/2018    167
2/15/2020     167
8/10/2018     167
8/28/2019     167
1/28/2018     167
9/11/2019     167
11/2/2017     167
3/14/2020     167
12/3/2018     167
5/16/2019     167
10/17/2018    167
10/31/2019    167
1/31/2017     167
2/26/2017     166
3/24/2018     166
1/15/2020     166
1/16/2019     166
10/25/2018    166
12/28/2019    166
1/11/2017     166
9/20/2017     166
7/6/2018      166
10/6/2017     166
2/26/2018     166
4/18/2018     166
9/29/2019     166
3/27/2019     166
3/23/2017     166
12/6/2018     166
7/20/2018     166
3/26/2017     166
3/18/2020     166
6/22/2019     166
1/10/2018     166
6/29/2017     166
2/15/2019     166
6/24/2018     166
8/17/2018     166
1/28/2020     166
3/9/2017      166
9/13/2019     166
1/29/2017     166
12/17/2017    166
12/18/2019    166
5/5/2018      166
3/18/2018     166
6/19/2018     165
1/14/2020     165
2/11/2018     165
2/28/2017     165
5/24/2019     165
8/29/2019     165
3/18/2017     165
2/14/2017     165
10/13/2018    165
12/6/2017     165
9/23/2017     165
11/22/2018    165
2/5/2020      165
1/30/2020     165
7/26/2018     165
3/27/2017     165
10/14/2017    165
3/30/2020     165
4/23/2018     165
8/17/2017     165
3/16/2019     165
1/29/2019     165
7/9/2017      165
5/25/2018     165
2/25/2020     165
9/8/2017      165
3/27/2020     165
12/26/2018    165
9/22/2018     165
7/8/2019      165
7/19/2018     165
1/5/2020      165
4/12/2018     164
2/10/2019     164
7/22/2019     164
6/26/2019     164
11/26/2018    164
9/7/2019      164
7/25/2019     164
12/8/2018     164
9/18/2017     164
1/17/2019     164
9/8/2018      164
8/8/2018      164
12/27/2019    164
12/13/2018    164
4/9/2017      164
2/16/2020     164
10/7/2018     164
9/16/2018     164
1/24/2020     164
1/9/2020      164
10/22/2018    164
11/4/2019     164
2/11/2017     164
2/11/2019     164
11/15/2018    164
2/21/2019     164
3/21/2019     164
9/2/2017      164
9/16/2019     164
1/15/2019     164
10/16/2017    164
11/13/2017    164
11/24/2018    164
3/27/2018     163
2/2/2020      163
1/27/2019     163
12/9/2018     163
8/21/2017     163
8/12/2017     163
2/21/2017     163
4/30/2019     163
12/27/2017    163
5/13/2018     163
3/1/2019      163
12/25/2018    163
7/1/2017      163
5/15/2019     163
5/4/2019      163
2/2/2018      163
6/12/2017     163
1/6/2020      163
10/13/2017    163
4/28/2017     163
6/29/2019     163
8/16/2017     163
3/30/2018     162
9/15/2019     162
6/2/2017      162
9/4/2018      162
3/9/2018      162
10/11/2018    162
12/15/2019    162
10/16/2018    162
3/2/2017      162
2/7/2017      162
11/10/2018    162
8/21/2018     162
7/14/2017     162
5/5/2019      162
8/22/2019     162
1/29/2018     162
11/29/2017    162
2/22/2020     162
5/29/2017     162
7/9/2018      162
3/29/2018     162
7/25/2017     161
11/19/2017    161
7/15/2018     161
3/5/2017      161
4/25/2017     161
10/26/2019    161
2/18/2019     161
11/3/2019     161
12/12/2018    161
12/16/2017    161
12/5/2018     161
8/29/2018     161
6/27/2018     161
3/22/2017     161
1/2/2020      161
11/4/2017     161
12/29/2017    161
6/17/2017     161
7/15/2019     161
5/10/2017     161
9/30/2018     161
1/18/2018     161
7/20/2019     160
1/28/2019     160
11/9/2019     160
3/29/2019     160
9/29/2017     160
2/21/2018     160
2/23/2017     160
11/3/2018     160
12/31/2018    160
12/18/2017    160
10/31/2017    160
8/27/2018     160
11/13/2018    160
8/1/2018      160
2/25/2019     160
11/29/2018    160
11/14/2018    160
6/27/2017     160
7/7/2019      160
3/10/2018     160
5/8/2017      160
1/21/2020     160
5/21/2019     160
3/30/2017     159
5/19/2019     159
12/30/2017    159
1/19/2018     159
6/13/2018     159
6/7/2017      159
2/9/2018      159
9/3/2019      159
4/22/2017     159
4/8/2018      159
6/18/2018     159
9/14/2019     159
8/9/2018      159
10/9/2017     159
1/1/2017      159
5/12/2018     158
1/10/2020     158
11/11/2018    158
1/16/2017     158
11/9/2017     158
3/24/2019     158
3/2/2019      158
7/12/2019     158
2/20/2017     158
7/21/2017     158
7/3/2018      158
2/15/2017     158
12/3/2017     158
12/15/2017    158
6/9/2018      158
7/12/2018     158
5/15/2018     158
1/6/2019      158
5/22/2017     158
9/8/2019      158
6/21/2018     158
4/26/2019     157
9/26/2017     157
10/14/2019    157
7/5/2017      157
8/22/2017     157
1/18/2020     157
3/26/2019     157
11/12/2019    157
2/27/2020     157
12/14/2019    157
2/15/2018     157
6/12/2019     157
10/25/2017    157
11/18/2018    157
3/20/2019     157
7/13/2019     157
9/7/2018      156
5/7/2017      156
11/8/2017     156
4/15/2019     156
3/16/2018     156
11/6/2017     156
4/16/2018     155
1/29/2020     155
1/14/2017     155
11/11/2017    155
12/14/2017    155
7/27/2019     155
5/20/2019     155
8/24/2018     155
9/5/2018      155
3/31/2018     155
6/14/2017     155
12/24/2018    155
7/21/2019     155
5/1/2018      155
11/20/2019    155
9/18/2018     155
12/15/2018    155
1/2/2017      154
5/8/2019      154
7/4/2018      154

In [19]:
# Value count of "fam_status"
customers['fam_status'].value_counts(dropna = False)

married                             144906
single                               33962
divorced/widowed                     17640
living with parents and siblings      9701
Name: fam_status, dtype: int64

In [20]:
# Confirm shape of dataset
customers.shape

(206209, 10)

# 4. Merge data

In [21]:
# Quick visual check of "customers"
customers.head()

,user_id,First Name,Last Name,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [22]:
# Quick visual check of ords_prods_merged
ords_prods_merged.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,...,prices,price_range_loc,busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_spent,spending_flag,order_frequency,frequency_flag
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,9.0,Mid-range product,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,9.0,Mid-range product,Slowest days,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,9.0,Mid-range product,Slowest days,Most orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,9.0,Mid-range product,Slowest days,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,9.0,Mid-range product,Slowest days,Most orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer

In [23]:
# Drop unnecessary columns to save memory and make merging easier
ords_prods_merged=ords_prods_merged.drop(columns=['avg_spent', 'order_frequency'])

##### My computer kept stalling and then crashing when trying to merge in the way we've been taught so far. My tutor came up with the following alternative method.

In [24]:
customers.drop_duplicates(subset ='user_id', keep = False, inplace = True) 
ords_prods_merged.drop_duplicates( keep = False, inplace = True)

In [25]:
# creating a empty bucket to save result
df_result = pd.DataFrame(columns=(ords_prods_merged.columns.append(customers.columns)).unique())
df_result.to_csv("df3.csv",index_label=False)

# save data which only appear in df1 # sorry I was doing left join here. no need to run below two line.
# df_result = df1[df1.Colname1.isin(df2.Colname2)!=True]
# df_result.to_csv("df3.csv",index_label=False, mode="a")

# deleting df2 to save memory
del(customers)

def preprocess(x):
    df2=pd.merge(ords_prods_merged,x, left_on = "user_id", right_on = "user_id")
    df2.to_csv("df3.csv",mode="a",header=False,index=False)

reader = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'customers.csv'), chunksize=1000) # chunksize depends with you colsize

[preprocess(r) for r in reader]

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [26]:
# Load merged dataset
bigmerged = pd.read_csv(os.path.join(path, '03 Scripts', 'df3.csv'))

In [27]:
# Quick visual check of merged dataset
bigmerged.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,...,frequency_flag,First Name,Last Name,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,3144955,10331,4,5,11,30.0,196,3,0,Soda,...,Regular customer,Marilyn,Olsen,Female,North Dakota,24,1/6/2017,3,married,73639
1,2300470,10331,1,2,14,NaN,21386,2,0,Smartwater,...,Regular customer,Marilyn,Olsen,Female,North Dakota,24,1/6/2017,3,married,73639
2,1922742,10331,2,5,11,10.0,21386,2,1,Smartwater,...,Regular customer,Marilyn,Olsen,Female,North Dakota,24,1/6/2017,3,married,73639
3,2300470,10331,1,2,14,NaN,42500,1,0,Orange & Lemon Flavor Variety Pack Sparkling F...,...,Regular customer,Marilyn,Olsen,Female,North Dakota,24,1/6/2017,3,married,73639
4,1922742,10331,2,5,11,10.0,42500,3,1,Orange & Lemon Flavor Variety Pack Sparkling F...,...,Regular customer,Marilyn,Olsen,Female,North Dakota,24,1/6/2017,3,married,73639

# 5. Export data

In [28]:
# Export dataframe
bigmerged.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'bigmerged_4.9.1.pkl'))